server:
  port: 8236
  
spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:orders_db
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  
 

  